print("What is your name human?")
name = str(input())
print()
print("How old are you (in years)?")
age = int(input())
print()
print("How tall are you (in meters)?")
height = int(input())
print()
print("How much do you weigh (in kilograms)?")
weigh = int(input())
bmi = weigh/(height**2)
print()
print(name+" you are "+str(age)+" years old and your bmi is "+str(bmi)+".")